### ISSUE TITLE
Use you plugin with CesiumWidget ?

### ISSUE THREAD

**Issue by iSergio** [alberto-acevedo/cesium-navigation#3]
Thanks for the cool plugin. But can a use it with CesiumWidget out from box ? Or i must change it to use with CesiumWidget ?

**Comment by alberto-acevedo** [comment]
I tested  and rotating or changing the orbit of the map with the compass works fine. There are issues with the events listeners not picking up the map moved events when using the widget. For example, when you rotate the map the compass should update accordingly but it is not updating. I think the issue is with the Cesium eventHelper.  When I have some free time I will work on a fix.  Thanks.

**Comment by alberto-acevedo** [comment]
I tried the latest version of the plugin using the CesiumWidget and it is working fine. In the demo page I testd like this:

//var viewer = new Cesium.Viewer('cesiumContainer');
//navigationInitialization('cesiumContainer', viewer);

var widget = new Cesium.CesiumWidget('cesiumContainer',
{
     imageryProvider: new Cesium.TileMapServiceImageryProvider({
                            url:: 'javascript/Cesium/Assets/Texture/NaturalEarthII'
             })
});
navigationInitialization('cesiumContainer', widget );
